Failure # 1 (occurred at 2024-11-04_18-49-33)
[36mray::ImplicitFunc.train()[39m (pid=82147, ip=172.24.11.109, actor_id=ab8cd9cd91dffd70e8b3b60101000000, repr=train)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/kgreedy/lib/python3.12/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/kgreedy/lib/python3.12/site-packages/ray/air/_internal/util.py", line 104, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/kgreedy/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/kgreedy/lib/python3.12/site-packages/ray/tune/trainable/function_trainable.py", line 250, in _trainable_func
    output = fn()
             ^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/kgreedy/lib/python3.12/site-packages/ray/tune/trainable/util.py", line 130, in inner
    return trainable(config, **fn_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/main.py", line 77, in train
    intial_metrics = agent.evaluate(testing_data, testing_labels)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/digvijay/Documents/developer/greedy_kernel_alignment/utils/agent.py", line 252, in evaluate
    'executions': self._per_epoch_executions,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrainModel' object has no attribute '_per_epoch_executions'
